services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - .:/home/dev/app:cached
    ports:
      - 9000:9000

    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/user/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOSTNAME: localhost

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
